-- MySQL Script generated by MySQL Workbench
-- Fri Mar  5 17:56:49 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TipoEvento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoEvento` (
  `idTipoEvento` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(200) NULL,
  PRIMARY KEY (`idTipoEvento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Eventos` (
  `idEventos` INT NOT NULL,
  `IdTipoEvento` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `fecha` DATE NULL,
  `Lugar` VARCHAR(200) NULL,
  `Cliente` VARCHAR(45) NULL,
  `Contactos` VARCHAR(45) NULL,
  PRIMARY KEY (`idEventos`),
    FOREIGN KEY (`IdTipoEvento`)
    REFERENCES `mydb`.`TipoEvento` (`idTipoEvento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empresa` (
  `idEmpresa` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Telefono` VARCHAR(8) NULL,
  `Direccion` VARCHAR(100) NULL,
  `Email` VARCHAR(45) NULL,
  `Logo_Url` LONGTEXT NULL,
  PRIMARY KEY (`idEmpresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipo_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo_Usuario` (
  `idTipo_Usuario` INT NOT NULL,
  `Tipo_Usuario` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipo_Usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `Usuario` VARCHAR(45) NULL,
  `Id_tipo_usuario` INT NOT NULL,
  `contraseña` VARCHAR(20) NULL,
  PRIMARY KEY (`idUsuario`),
    FOREIGN KEY (`Id_tipo_usuario`)
    REFERENCES `mydb`.`Tipo_Usuario` (`idTipo_Usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Servicios` (
  `idServicios` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(300) NULL,
  `urlIMG` LONGTEXT NULL,
  `IdEmpresa` INT NOT NULL,
  `Id_Usuario` INT NOT NULL,
    FOREIGN KEY (`IdEmpresa`)
    REFERENCES `mydb`.`Empresa` (`idEmpresa`),
    FOREIGN KEY (`Id_Usuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `mydb`.`InfoServicios` (
  `idEmpresa` INT NOT NULL,
  `HeaderTitulo` VARCHAR(50) NULL,
  `DescripcionHeader` VARCHAR(200) NULL,
  PRIMARY KEY (`idEmpresa`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
